name: ProductivityApp
options:
  bundleIdPrefix: com.productivity
  deploymentTarget:
    iOS: 17.0
targets:
  ProductivityApp:
    type: application
    platform: iOS
    sources: 
      - ProductivityApp
    settings:
      base:
        INFOPLIST_FILE: ProductivityApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.productivity.app
